### ISSUE TITLE
Win 10 + minter 0.5.0 Panicked on a Sanity Check

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-go-node#124]
panic: Panicked on a Sanity Check: Error opening Mempool wal file: file: [C:\Users\admin\.minter\tmdata\mempool.wal/wal]
expected file permissions: -rw-------, got: -rw-rw-rw-

**Comment by jamwid07** [comment]
I've got same issue
Does anybody from developers checked this?

**Comment by danil-lashin** [comment]
https://github.com/tendermint/tendermint/issues/2717

**Comment by danil-lashin** [comment]
Closing as fixed in https://github.com/tendermint/tendermint/issues/2717
