### ISSUE TITLE
First time user experience issues

### ISSUE THREAD

**Issue by melekes** [MinterTeam/minter-go-node#128]
## 1. user: Current not implemented on linux/amd64

When I've tried to run a freshly downloaded binary (same when building from source), I got:

```
root@f26985dca600:/go# ./minter
panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/MinterTeam/minter-go-node/cmd/utils.GetMinterHome(0xc, 0x0)
        /Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/cmd/utils/flags.go:32 +0x10b
github.com/MinterTeam/minter-go-node/config.init.0()
        /Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/config/config.go:30 +0x26
```

Env:

```
uname -a
Linux f26985dca600 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
minter 0.6.0
# go version
go version go1.10.4 linux/amd64
docker run --rm -it golang:1.10 /bin/bash
Client: Docker Engine - Community
 Version:           18.09.0-ce-beta1
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        78a6bdb
 Built:             Thu Sep  6 22:41:53 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0-ce-beta1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       78a6bdb
  Built:            Thu Sep  6 22:49:35 2018
  OS/Arch:          linux/amd64
  Experimental:     true

```

## 2. docs: use -p when creating multiple directories

When installing from source, it should be

```
mkdir -p $GOPATH/src/github.com/MinterTeam
```

without `-p` flag, it will throw an error

```
mkdir: cannot create directory '/go/src/github.com/MinterTeam': No such file or directory
```

## 3. docs: tendermint update

`Tendermint is known to open more than 1024 files.` https://minter-go-node.readthedocs.io/en/dev/install.html#too-many-open-files-24

That is not true anymore (at least for the past 3 versions). Please file an issue otherwise!

**Comment by melekes** [comment]
Re 1:

It looks like I should compile with CGO https://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64

**Comment by melekes** [comment]
Re 1:

When compiled with CGO (`CGO_ENABLED=1`), it works.

**Comment by nohchoesliche** [comment]
Why are you texting me? I don't understand what your messages say. Explain.



пн, 5 нояб. 2018 г. в 17:50, Anton Kaliaev <notifications@github.com>:

**Comment by danil-lashin** [comment]
Thanks, all fixed! Will be merged to master in next release.
