### ISSUE TITLE
external access to gui

### ISSUE THREAD

**Issue by akudryav** [MinterTeam/minter-go-node#149]
I've installed minter on  Google Cloud Platform VM.
How could I access minter GUI interface from the outside, not http://localhost:3000 ?

I have set up nginx and configure proxy for 3000 port:
location /{
        proxy_pass http://localhost:3000;
    }
but it returns 404 error only. 
And if I use curl localhost:3000 from server console it returns valid html

**Comment by danil-lashin** [comment]
@akudryav, thank you for issue!

If ports are open on machine then you can access GUI by visiting http://node-ip:3000 in your browser.

Anyway, this is not related to Minter Node itself, so you should refer to your system administrator or devops. Also you can ask for help in our [official chat](https://t.me/joinchat/EafyEVD-HEOxDcv8YyaqNg) in Telegram.

**Comment by akudryav** [comment]
Ok it works, by the way you also need open port 8841 (in firewall) to get info about the node.
