### ISSUE TITLE
Error "Dialing failed"

### ISSUE THREAD

**Issue by lehatrushin** [MinterTeam/minter-go-node#150]
I'm trying to run a minter on windows server 2016 x64. Run as administrator. When I start, I get the error "Dialing failed". Tried to add inbound/outbound rules for the application in the firewall. Just turned off the firewall. Does not help. This is screenshot
![1](https://user-images.githubusercontent.com/12657085/48538370-5827ba00-e8c5-11e8-92bc-06044b615b7e.jpg)
And have no peers
![2](https://user-images.githubusercontent.com/12657085/48538759-63c7b080-e8c6-11e8-8959-75d0ae9ff568.jpg)

**Comment by danil-lashin** [comment]
Hi!
Seed node was offline, sorry about that. Now everything should work correctly.

**Comment by lehatrushin** [comment]
> Hi!
> Seed node was offline, sorry about that. Now everything should work correctly.

Yes, now it's ok
