### ISSUE TITLE
Permanent error "pong timeout"

### ISSUE THREAD

**Issue by lehatrushin** [MinterTeam/minter-go-node#157]
Use latest release 0.7.1 on Windows Server 2016 Datacenter x64. **Is Synced = Yes**. Constant error appears (something like that):
**Connection failed @ sendRoutine              module=p2p peer=24fe4414f92741dc232facc4c10704b3446edf11@0.0.0.0:26656 conn=MConn{136.243.33.21:26656} err="pong timeout"**
I tried everything. Turned off the firewall, deleted the entire blockchain cache and downloaded again. Nothing helps. Stiil have validator status **Down**. And transaction **SET CANDIDATE ON** successfully completed.

![image](https://user-images.githubusercontent.com/12657085/48664741-56701900-eab4-11e8-9877-2e71a062b349.png)

**Comment by danil-lashin** [comment]
Sorry for the late answer. This is absolutely normal behavior. Some nodes may not respond to your requests.
