### ISSUE TITLE
How to update the version of the application?

### ISSUE THREAD

**Issue by akudryav** [MinterTeam/minter-go-node#162]
Hi. I use google cloud VM on Ubuntu.
After the release of the new version of the application, in some time the old version launched on the server freezes (the Latest Block Height stops increasing).
A simple update of the executable file and its restarting does not help, errors start to pour in the console or the application does not start at all.
You have to completely delete the directory ./minter, synchronize again and apply for registration new masternode. At the same time, I understand that all the history of previous validations is lost and Voting Power is reset. On a test network, this is probably not critical, but how to be after launching a production one?

**Comment by danil-lashin** [comment]
Hi! There was an error in versions 0.7.1, 0.7.2. Now you should be able to upgrade smoothly.
