### ISSUE TITLE
Downloading blocks does not work

### ISSUE THREAD

**Issue by lehatrushin** [MinterTeam/minter-go-node#180]
OS Ubuntu  18.10, firewall off, minter 0.8.4.
This is information from the status of the node:

Node Info
Node ID | 35c4c30924262dfd8ca11b6072a3e761432f8e33
Network ID | minter-test-network-27
Minter Version | 0.8.4-777e78cf
Tendermint Version | 0.27.0

Net Info
Is Listening |  yes
Connected Peers | 1

Syncing Info
Is Synced | No
Latest Block Height | #0 of 16448
Latest Block Time | 1970-01-01T00:00:00Z

As you can see, there is only one peer. And as I understand it is myself. The node is not connected to the network. Blocks do not download. In the node logs there are only "pong timeout" errors. Approximately 1 error per minute. But as you answered me [here ](https://github.com/MinterTeam/minter-go-node/issues/157) it seems to be as normal. No other entries. Why don't the blocks download?

UPD. All downloaded. Apparently there were some glitches

**Comment by danil-lashin** [comment]
Thanks for reporting! This can be happening because we have too little seed nodes. We'll increase their amount.
