### ISSUE TITLE
Masternode owner's address, where the reward will be accrued, is the same as masternode managment address

### ISSUE THREAD

**Issue by Hantok** [MinterTeam/minter-go-node#182]
When you declare masternode from address **A**, and set the masternode owner's address, where the reward will be accrued, to address **B**, you can not manage masternode commands like _SET CANDIDATE ON/OFF_ from the address **A**.

Step to reproduce:
1) Login to https://testnet.console.minter.network/masternode (let's say from address **A**)
2) Set a different address to the field: **Address** (let's say address **B**)

Current result:
The reward is accrued to address **B**.
Masternode management transactions allowed from address **B**.

Expected result:
The reward is accrued to address **B**.
Masternode management transactions allowed from address **A**.

**Comment by danil-lashin** [comment]
Will be shipped with v0.9.0.
