### ISSUE TITLE
Missing dependencies during "make get_tools" on my windows machine.

### ISSUE THREAD

**Issue by moon004** [MinterTeam/minter-go-node#185]
the command make get_tools give me missing github packages error on the first build, So i had added all the dependencies required on the scripts/get_tools.sh file, I would be glad to send u guys a PR.

ps: i found this project pretty interesting.

**Comment by moon004** [comment]
so i'll PR to your dev branch right sir?

**Comment by danil-lashin** [comment]
Yes, that would be perfect.
