### ISSUE TITLE
Can't start minter node on Mac

### ISSUE THREAD

**Issue by mazhiyu** [MinterTeam/minter-go-node#252]
$./minter
dyld: Library not loaded: /Users/daniillashin/Desktop/t/leveldb-1.20/libleveldb.dylib.1
Referenced from: xxxxx/./minter
Reason: image not found
Abort trap: 6

**Comment by danil-lashin** [comment]
You should install leveldb: https://github.com/google/leveldb

**Comment by mazhiyu** [comment]
Maybe it's load lib on the wrong path, "daniillashin" isn't my username

**Comment by danil-lashin** [comment]
Please use this gist to install leveldb: https://gist.github.com/danil-lashin/9df600cb2d1fe8e503aae60fc0d6e209
