### ISSUE TITLE
Расчет коэф-та конвертации

### ISSUE THREAD

**Issue by azimuth0x28** [MinterTeam/minter-go-node#69]
[Вычисляем через Данные Кандидата ](http://95.216.148.138:8841/api/candidate/Mp4ae1ee73e6136c85b0ca933a9a1347758a334885f10b3238398a67ac2eb153b8)
--
Исходные данные http://take.ms/dfDYR
PoolTotalStake | 2,01736E+23
Owner Bonded | 2E+23
Holder   MNT | 1E+21

Holder  Total = PoolTotalStake - Owner Bonded | 1,7361E+21

Holder  BELT (MNT-pip )=  Holder  Total - Holder  MNT  | **7,36104E+20**

[Конвертируем MNT-pip  =>BELT -pip](http://95.216.148.138:8841/api/estimateCoinSell?coin_to_sell=MNT&value_to_sell=736104000000000000000&coin_to_buy=BELTCOIN)

BELT-pip | 5,82027E+18

BELT/MNT  Rate = BELT-pip / Holder  BELT (MNT-pip )  | **126,4724646**

[Теперь сверяем с данными конвертера ](http://95.216.148.138:8841/api/estimateCoinSell?coin_to_sell=BELTCOIN&value_to_sell=1000000000000000000&coin_to_buy=MNT)
---
BELT-pip | 1E+18
MNT-pip | 9,94301E+19

BELT/MNT   Rate = MNT-pip /  BELT-pip | **99,43013495**

ИТОГО  **126,4724646** != **99,43013495**

Возможно я где-то не прав. То поправьте.

**Comment by EvgeniyTaburyanskiy** [comment]
дополнение:
Версия сети 17


Пользуюсь все тем же [API ](http://95.216.148.138:8841/api/estimateCoinSell?coin_to_sell=BELTCOIN&value_to_sell=1000000000000000000&coin_to_buy=MNT)

Почему-то при конвертации монеты  получаем разный результат.
продаю порядком выше , получаю тоже порядком выше, но не совсем.

sel BELT |get MNT | Commission
1 | 2,21381E+16 | 4,60427E+18
10 | 2,11091E+17 | 4,60427E+18
100 | 1,34786E+18 | 4,60427E+18

**Comment by danil-lashin** [comment]
Следует учесть несколько моментов.

1. При конвертации разного кол-ва монет результат будет разный

> sel BELT |get MNT | Commission
> 1 | 2,21381E+16 | 4,60427E+18
> 10 | 2,11091E+17 | 4,60427E+18
> 100 | 1,34786E+18 | 4,60427E+18

2. Обратная конвертация возможна только после реального обмена монет в блокчейне, так как при продаже/покупке курс меняется.

> меняю BELT/MNT => 500 = 188.31
> меняю MNT/BELT=> 188.31 = 607.31
