### ISSUE TITLE
Minter не читает файл конфига .tendermint\config\config.toml

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-go-node#70]
- Minter Version [0.1.4]

https://github.com/MinterTeam/minter-go-node/blob/master/config/config.go

Правки файла config.toml не приводят ни к чему. 
Пытаюсь изменить для идетификации Ноды и защиты валидатора:
Moniker и p2p,laddr

**Comment by danil-lashin** [comment]
Конфигурации там больше нет. В следующем обновлении появится инструкция как менять настройки.
