### ISSUE TITLE
Пожелание к API минтера

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-go-node#76]
Приветствую.
Предлагаю добавить в выдачу endpoint  /api/candidate/ .....
Информацию о версии Тендерминта (tm_status) и минтера

Это удобно для отслеживания состояния валидаторов, не разглашая их IP
в случае sentryNode архитектуры, валидатор скрыт от сети. Но в целях мониторинга было бы удобно и это важно, видеть какая версия ноды работает у валидатора.
Сейчас это можно узнать только через прямой запрос к Минтеру работающему в паре с Блокчейном. А соответственно раскрываем IP.
Если все ноды будут знать о версиях По у Валидаторов, то без раскрытия IP, можно будет отслеживать соcтояние ПО Валидаторов.

**Comment by danil-lashin** [comment]
По публичному ключу невозможно определить IP адрес валидатора.
