### ISSUE TITLE
crash node in linux

### ISSUE THREAD

**Issue by wirwolf** [MinterTeam/minter-go-node#81]
**To Reproduce**
1. download bin file from github
2. unzip
3. launch one process
4. launch another process
```
wir_wolf@Developer-PC ~ $ ./minter_0.1.8_linux_amd64 
panic: resource temporarily unavailable

goroutine 1 [running]:
github.com/MinterTeam/minter-go-node/core/minter.NewMinterBlockchain(0xc4207c24e0)
        /Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/core/minter/minter.go:58 +0x242
main.main()
        /Users/daniillashin/go/src/github.com/MinterTeam/minter-go-node/cmd/minter/main.go:33 +0xb3


```

**Screenshots**
![screenshot_20180815_211853](https://user-images.githubusercontent.com/8457572/44165242-d612d400-a0d0-11e8-864a-b2bae26c37b3.png)

**Desktop (please complete the following information):**
 - OS: KUbuntu 16.04.03
 - Minter Version v0.1.8

**Comment by danil-lashin** [comment]
For now it's only possible to run 1 instance of Minter Node at a time.
