### ISSUE TITLE
Расчет CUSTOM coin в MNT прошу пояснить

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-go-node#89]
**Describe the bug**

**To Reproduce**
Адрес Mx8d3c1212512bbb7e754e49e8d5880fc753a92762

смотрим Делегата в API
http://95.216.148.138:8841/api/candidate/Mp8f053f3802d33f5e7092bb01ca99ae77606f4faf759c72560d5ee69b8e191a56

owner: "Mx8d3c1212512bbb7e754e49e8d5880fc753a92762",
coin: "SHSCOIN",
value: "359245000000000000000000",
bip_value: "55214201947413662915536"

Получается что если продать 359245000000000000000000 то можно получить 55214201947413662915536

Проверяем 
http://95.216.148.138:8841/api/estimateCoinSell?coin_to_sell=SHSCOIN&value_to_sell=359245000000000000000000&coin_to_buy=MNT

will_get: "74821901820913662915536",

Почему расходятся цифры , баг ли это или все Ок ?
если ок, то как можно получить 55214201947413662915536, через какой эндпоинт API ?

 - Minter Version 0.2.3

**Comment by danil-lashin** [comment]
Это не баг.

- Вес стейка из кастомных монет теперь пересчитывается следующим образом:
 1. Суммируются все подобные монеты делегированные на все ноды
 2. Вычисляется сумма, которую можно получить при их одновременной продаже
 3. Эта сумма пропорционально распределяется между делегаторами этих монет
