### ISSUE TITLE
Не сходятся суммы делегированные при просчете по формуле и запросом по API

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-go-node#92]
**To Reproduce**

### Через запрос по [API](http://95.216.148.138:8841/api/candidate/Mp8f053f3802d33f5e7092bb01ca99ae77606f4faf759c72560d5ee69b8e191a56)
получаю список делегаторов.
Выбираю произвольного с SHSCION 
http://take.ms/QaXye

value: "292666000000000000000000",
bip_value: "53180217160045527885907"

**Результат Запроса: 53180217160045527885907**

### Проверяю Формулу:
Делаю запрос по [API](http://95.216.148.138:8841/api/coinInfo/SHSCOIN)
Получаю

symbol: "SHSCOIN",
volume: "1788176875639295577530972",
crr: 50,
reserve_balance: "319757654110053536997683",

Делаю расчет по формуле из Документации  [CalculateSaleReturn](https://minter-go-node.readthedocs.io/en/dev/coins.html#coin-exchange)

Array
(
    [$sPipAmountFrom] => 292666000000000000000000
    [$arCoinHitCache] => Array
        (
            [SHSCOIN] => Array
                (
                    [name] => Stakeholder Coin
                    [symbol] => SHSCOIN
                    [volume] => 1788176875639295577530972
                    [crr] => 50
                    [reserve_balance] => 319757654110053536997683
                    [creator] => Mx6eadf5badeda8f76fc35e0c4d7f7fbc00fe34315
                )

        )

    [$sSupplyPip] => 1788176875639295577530972
    [$fCrr] => 0.5
    [$sReserveBaseCoinPip] => 319757654110053536997683
    [$sSellAmountPip] => 1788176875639295577530972
    [$sSaleReturnBaseCoinPip] => 319757654110053536997683
    [$sDelegatedRatio] => 0.163667254613930877
    [$sResult] => 52333857389983373208646
)

**Результат Формулы  52333857389983373208646**

52333857389983373208646 !== 53180217160045527885907

Что я упустил ?

 - Minter Version [0.2.3]

**Comment by danil-lashin** [comment]
Уже был вопрос в #89
